### ISSUE TITLE
[Feature] Supporting raw yuv videos

### ISSUE THREAD

**Issue by hofbi** [slhck/siti#3]
Calling siti on a raw yuv video results in

```shell
siti akiyo_cif.yuv
Picture size 0x0 is invalid
Traceback (most recent call last):
  File "~/.local/bin/siti", line 8, in <module>
    sys.exit(main())
  File "~/.local/lib/python3.8/site-packages/siti/__main__.py", line 148, in main
    si_orig, ti_orig, num_frames = calculate_si_ti(
  File "~/.local/lib/python3.8/site-packages/siti/__main__.py", line 81, in calculate_si_ti
    container = av.open(input_file)
  File "av/container/core.pyx", line 249, in av.container.core.open
  File "av/container/core.pyx", line 210, in av.container.core.Container.__cinit__
  File "av/container/core.pyx", line 111, in av.container.core.ContainerProxy.__init__
  File "av/container/core.pyx", line 182, in av.container.core.ContainerProxy.err_check
  File "av/utils.pyx", line 103, in av.utils.err_check
av.AVError: [Errno 22] Invalid argument: 'akiyo_cif.yuv' (libav.IMGUTILS: Picture size 0x0 is invalid)
```

Supporting raw images would require the additional optional arguments width, height and format such as used in https://github.com/Telecommunication-Telemedia-Assessment/SITI

Current solution is to use https://github.com/Telecommunication-Telemedia-Assessment/SITI, however it would be more convenient if this would be also supported by the python package.

**Comment by slhck** [comment]
That would indeed be a nice feature, however I don't see how you can use PyAV to open a raw input file and specify the frame dimensions and pixel format like you can with `ffmpeg`. Do you have any idea?

In the meantime I suggest wrapping the YUV files with:

```bash
ffmpeg -f rawvideo -s 320x240 -r 25 -i input.yuv output.avi
```

**Comment by hofbi** [comment]
I checked the PyAV code but could not find a way to specify the video size. I never used it before, so I might have missed something. I went through the container arguments [here](https://github.com/PyAV-Org/PyAV/blob/main/av/container/core.pyx#L101) to find something.

Thank you for the hint. I gave it a try. Unfortunetly I run in another issue

```shell
  File "~/.local/bin/siti", line 8, in <module>
    sys.exit(main())
  File "~/.local/lib/python3.8/site-packages/siti/__main__.py", line 148, in main
    si_orig, ti_orig, num_frames = calculate_si_ti(
  File "~/.local/lib/python3.8/site-packages/siti/__main__.py", line 99, in calculate_si_ti
    frame_data = frame.to_ndarray(format="gray").reshape(frame.height, frame.width).astype("float32")
AttributeError: 'av.video.frame.VideoFrame' object has no attribute 'to_ndarray'
```

**Comment by slhck** [comment]
Hm, do you  have the latest version of the dependencies? `to_ndarray` has been part of `av` for as long as as this project exists.

I just released 1.0.7 which should have more strict dependencies, please try this.

**Comment by slhck** [comment]
PS: Of course, if you have a YUV file you can skip the whole PyAV part and read the frames directly, but that'd require some additional logic, especially for different raw formats.

**Comment by slhck** [comment]
There is a work-in-progress branch at https://github.com/slhck/siti/tree/add-yuv where I added support for YUV420-encoded raw video.

I still have to verify the numbers, in particular what the `format="gray"` function in PyAV does (i.e. whether it simply returns the Y plane, or whether it applies a correction function).

**Comment by hofbi** [comment]
I updated to the latest version 1.0.7, but still get the same error. I have these versions of the dependencies installed

* tqdm 4.50.2
* scipy 1.3.3
* numpy 1.19.2
* pyav 0.4.5

For now I already solved my problem by using the cpp siti version. But in general having yuv support makes sense.

**Comment by slhck** [comment]
I unfortunately cannot reprodue the `to_ndarray` issue. Will try on another system later.

I updated the YUV branch, but it produces different values from the main function, so that maybe requires format conversion between the color planes.

**Comment by hofbi** [comment]
I get this error on an Ubuntu 20.04 with python 3.8.

**Comment by slhck** [comment]
Version 1.1.0 now has YUV file support, albeit with different values obtained for the same file – see #4 for some background.

I cannot reproduce your issue. Please make sure that you have a clean Python environment to test, perhaps by removing all depenndencies and re-installing `siti` (which should pull the correct deps). Ideally install the dependencies in a virtualenv for checking, e.g.:

```
$ python3 -m venv env
$ source env/bin/activate
$ pip3 install siti
Collecting siti
  Downloading https://files.pythonhosted.org/packages/e2/e6/761c398a6df5ef695878fccdb4b4fdc373d9e410da6759477d82eeb797ba/siti-1.0.7-py3-none-any.whl
Collecting tqdm (from siti)
  Using cached https://files.pythonhosted.org/packages/bd/cf/f91813073e4135c1183cadf968256764a6fe4e35c351d596d527c0540461/tqdm-4.50.2-py2.py3-none-any.whl
Collecting av (from siti)
  Using cached https://files.pythonhosted.org/packages/6b/35/0fc3a5fec81d662c64158726e2b1c96acdcaa03ff771ba70309dbc516823/av-8.0.2-cp38-cp38-macosx_10_9_x86_64.whl
Collecting numpy (from siti)
  Using cached https://files.pythonhosted.org/packages/33/1a/d10d1c23d21c289a3e87e751a9daf0907e91665cab08d0c35033fd4f5b55/numpy-1.19.2-cp38-cp38-macosx_10_9_x86_64.whl
Collecting scipy (from siti)
  Using cached https://files.pythonhosted.org/packages/8a/84/568ec7727bc789a9b623ec2652043ad3311d7939f152e81cb5d699bfb9b1/scipy-1.5.2-cp38-cp38-macosx_10_9_x86_64.whl
Installing collected packages: tqdm, av, numpy, scipy, siti
Successfully installed av-8.0.2 numpy-1.19.2 scipy-1.5.2 siti-1.0.7 tqdm-4.50.2
$ ./env/bin/siti /path/to/file.mp4
$ deactivate
$ rm -rf ./env
```

**Comment by hofbi** [comment]
I updated to the latest version 1.1.0. The remaining environment did not change. Now the issue is gone.

**Comment by slhck** [comment]
Thanks for confirming!
